---
title: "EDS212 Day 4 Morning"
author: "Rachel Swick"
format: html
chunk_output_type: console
---

## Create matrices in R

```{r}
# create sequence of values ----
my_values <- seq(from = 1, to = 10, by = 1)
my_values

# convert to matrix ----
my_matrix <- matrix(data = my_values, 
                    nrow = 2, 
                    ncol = 5,
                    byrow = TRUE)
class(my_matrix)
```

## Incorrectly declared matrix sizes

```{r}
# will still create our matrix for us, but gives us a warning message that the data length is not a sub-mutiple of multiple of the number of columns
matrix(data = my_values, nrow = 2, ncol = 3, byrow = TRUE)

# will still create our matrix, but will just start repeating sequence
matrix(data = my_values, nrow = 2, ncol = 15, byrow = TRUE)
```

## Lets do some math with matrices

```{r}
# scalar multiplication ----
4 * my_matrix

# let's create a second matrix ----
my_values2 <- seq(from = 21, to = 30, by = 1)
my_matrix2 <- matrix(data = my_values2, nrow = 2, ncol = 5, byrow = TRUE)
my_matrix2

# add matricies ----
my_matrix2 + my_matrix

# subtract matricies ----
my_matrix2 - my_matrix

# dot products of matrices ----
my_matrix * my_matrix2
```

```{r}
# make a couple of 2x2 matrices ----
cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, ncol = 2, byrow = TRUE)
dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)

cats %*% dogs
```

## Leslie matrix example

```{r}
# create the matrix ----
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), nrow = 3, ncol = 3, byrow = TRUE)

# inital starting conditions ----
insect_y0 <- c(12000, 700, 500)

# pop at year 1 ----
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# pop at year 2 ----
insect_y2 <- insect_leslie %*% insect_y1
insect_y2

# pop at year 3 ----
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
```

## Another Leslie matrix

```{r}
# create the matrix ----
tree_leslie <- matrix(data = c(0, 0, 5000, 0.1, 0, 0, 0, 0.06, 0.95), nrow = 3, ncol = 3, byrow = TRUE)
tree_leslie

# inital starting conditions ----
tree_y0 <- c(5000, 0, 0)

# pop at year 1 ----
tree_y1 <- tree_leslie %*% tree_y0
tree_y1

tree_y2 <- tree_leslie %*% tree_y1
tree_y2

tree_y3 <- tree_leslie %*% tree_y2
tree_y3
```





















